export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  CONTENT_REJECTED: 'CONTENT_REJECTED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export const ERROR_MESSAGES = {
  AUTH_REQUIRED: '인증이 필요합니다.',
  ACCOUNT_SUSPENDED: '커뮤니티 운영 정책 위반으로 이용이 제한된 계정입니다.',
  CONTENT_REJECTED: '커뮤니티 운영 정책에 맞지 않는 내용이 포함되어 있습니다. 내용을 수정해 주세요.',
  DATABASE_ERROR: '데이터 처리 중 오류가 발생했습니다.',
  ENDED_TRAVEL_SESSION_CANNOT_ACTIVATE: '종료된 여행 세션은 다시 활성화할 수 없습니다.',
  FILE_UPLOAD_INVALID: '파일 업로드 요청이 올바르지 않습니다.',
  FORBIDDEN: '요청한 작업을 수행할 권한이 없습니다.',
  IDEMPOTENCY_IN_PROGRESS: '동일한 요청이 아직 처리 중입니다.',
  INTERNAL_SERVER_ERROR: '서버 오류가 발생했습니다.',
  INVALID_EMAIL_OR_PASSWORD: '이메일 또는 비밀번호가 올바르지 않습니다.',
  INVALID_REFRESH_TOKEN: 'refresh token이 유효하지 않습니다.',
  INVALID_REQUEST: '요청 값이 올바르지 않습니다.',
  INVALID_TOKEN: '유효하지 않은 토큰입니다.',
  MODERATION_ADMIN_NOT_CONFIGURED: '신고 운영 관리자 인증이 설정되지 않았습니다.',
  PHOTO_REQUIRED: 'photo 파일이 필요합니다.',
  PLAYLIST_NOT_FOUND: '플레이리스트를 찾을 수 없습니다.',
  MOMENT_LOG_NOT_FOUND: 'Moment Log를 찾을 수 없습니다.',
  USER_ALREADY_EXISTS: '이미 가입된 이메일입니다.',
  RECAP_NOT_FOUND: '리캡을 찾을 수 없습니다.',
  RECAP_LOG_REQUIRES_CAPTURE: '여행 로그에는 하나 이상의 리캡이 필요합니다.',
  RECAP_LOG_CAPTURE_MISMATCH: '요청한 리캡이 여행 세션과 일치하지 않습니다.',
  RECAP_LOG_PUBLIC_CAPTURE_REQUIRED: '전체공개 로그에는 공개 위치가 있는 리캡이 하나 이상 필요합니다.',
  RECAP_THUMBNAIL_LOG_REQUIRED: '여행 로그만 썸네일을 지정할 수 있습니다.',
  RECAP_THUMBNAIL_MOMENT_NOT_FOUND: '로그에 포함된 리캡만 썸네일로 지정할 수 있습니다.',
  RECAP_PUBLIC_LOCATION_REQUIRED: '전체공개 리캡은 대표 위치가 필요합니다.',
  RECOMMENDATION_TRACK_NOT_FOUND: '추천 트랙을 찾을 수 없습니다.',
  REGION_SOUND_TREND_NOT_FOUND: '지역 사운드 트렌드를 찾을 수 없습니다.',
  REPRESENTATIVE_TRACK_NOT_FOUND: '대표 트랙을 찾을 수 없습니다.',
  RESOURCE_NOT_FOUND: '요청한 리소스를 찾을 수 없습니다.',
  ROUTE_NOT_FOUND: '요청한 API 경로를 찾을 수 없습니다.',
  TRACK_NOT_FOUND: '트랙을 찾을 수 없습니다.',
  TRAVEL_MATE_REQUEST_ACTION_NOT_ALLOWED: '이 동행 매칭 요청을 처리할 권한이 없습니다.',
  TRAVEL_MATE_REQUEST_BLOCKED: '차단 관계의 사용자에게는 동행 매칭 요청을 보낼 수 없습니다.',
  TRAVEL_MATE_REQUEST_NOT_PENDING: '대기 중인 동행 매칭 요청만 변경할 수 있습니다.',
  TRAVEL_MATE_REQUEST_NOT_FOUND: '동행 매칭 요청을 찾을 수 없습니다.',
  TRAVEL_MATE_REQUEST_RATE_LIMITED: '최근 처리된 동행 매칭 요청이 있어 잠시 후 다시 시도할 수 있습니다.',
  TRAVEL_MATE_SELF_REQUEST_NOT_ALLOWED: '자기 자신에게는 동행 매칭 요청을 보낼 수 없습니다.',
  TRAVEL_MATE_TARGET_REQUIRED: '동행 매칭 대상이 필요합니다.',
  TRAVEL_ROOM_INVITE_CODE_INVALID: '여행방 초대 코드가 올바르지 않습니다.',
  TRAVEL_ROOM_MOMENT_NOT_FOUND: '공동 Recap 후보 Moment를 찾을 수 없습니다.',
  TRAVEL_ROOM_NOT_FOUND: '여행방을 찾을 수 없습니다.',
  TRAVEL_SESSION_ACTIVE_REQUIRED: '여행 모드가 켜진 활성 세션에서만 사용할 수 있습니다.',
  TRAVEL_SESSION_NOT_FOUND: '여행 세션을 찾을 수 없습니다.',
} as const;
