export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export const ERROR_MESSAGES = {
  AUTH_REQUIRED: '인증이 필요합니다.',
  DATABASE_ERROR: '데이터 처리 중 오류가 발생했습니다.',
  ENDED_TRAVEL_SESSION_CANNOT_ACTIVATE: '종료된 여행 세션은 다시 활성화할 수 없습니다.',
  FILE_UPLOAD_INVALID: '파일 업로드 요청이 올바르지 않습니다.',
  IDEMPOTENCY_IN_PROGRESS: '동일한 요청이 아직 처리 중입니다.',
  INTERNAL_SERVER_ERROR: '서버 오류가 발생했습니다.',
  INVALID_EMAIL_OR_PASSWORD: '이메일 또는 비밀번호가 올바르지 않습니다.',
  INVALID_REFRESH_TOKEN: 'refresh token이 유효하지 않습니다.',
  INVALID_REQUEST: '요청 값이 올바르지 않습니다.',
  INVALID_TOKEN: '유효하지 않은 토큰입니다.',
  PHOTO_REQUIRED: 'photo 파일이 필요합니다.',
  PLAYLIST_NOT_FOUND: '플레이리스트를 찾을 수 없습니다.',
  USER_ALREADY_EXISTS: '이미 가입된 이메일입니다.',
  RECAP_NOT_FOUND: '리캡을 찾을 수 없습니다.',
  RECOMMENDATION_TRACK_NOT_FOUND: '추천 트랙을 찾을 수 없습니다.',
  REGION_SOUND_TREND_NOT_FOUND: '지역 사운드 트렌드를 찾을 수 없습니다.',
  REPRESENTATIVE_TRACK_NOT_FOUND: '대표 트랙을 찾을 수 없습니다.',
  RESOURCE_NOT_FOUND: '요청한 리소스를 찾을 수 없습니다.',
  ROUTE_NOT_FOUND: '요청한 API 경로를 찾을 수 없습니다.',
  TRACK_NOT_FOUND: '트랙을 찾을 수 없습니다.',
  TRAVEL_SESSION_NOT_FOUND: '여행 세션을 찾을 수 없습니다.',
} as const;
